project:
  type: website

website:
  title: "Group 4"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - text: Methodology
        menu: 
        - dataprep.qmd
        - before.qmd
        - during.qmd
        - after.qmd
        - resupply.qmd
      - href: results.qmd
        text: Results and Discussion
      - href: lessons.qmd
        text: Lessons Learnt
    right:
      - href: about.qmd
        text: About
        

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

