project:
  type: website

website:
  title: "Group 4"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: methodology.qmd
        text: Methodology
      - href: results.qmd
        text: Results and Discussion
      - href: lessons.qmd
        text: Lessons Learnt
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

